# SwiftLint Configuration for ExocortexTaskTracker

# Excluded paths
excluded:
  - Pods
  - build
  - .build
  - DerivedData
  - ExocortexTaskTracker.xcodeproj
  - ExocortexTaskTracker.xcworkspace

# Enabled rules
opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length

# Rule configurations
identifier_name:
  min_length: 1
  max_length: 60
  excluded:
    - id
    - url
    - URL
    - iOS

type_name:
  min_length: 3
  max_length: 60

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 100
  error: 150

type_body_length:
  warning: 300
  error: 500

cyclomatic_complexity:
  warning: 15
  error: 25

# Custom rules
custom_rules:
  no_print:
    name: "Print statements"
    regex: '\bprint\('
    message: "Use proper logging instead of print()"
    severity: warning
    excluded: ".*Tests\\.swift"
